import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'dark-navy': '#0A192F',
        'surface-container-high': '#eae7ea',
        'on-primary-fixed-variant': '#39475f',
        'on-error': '#ffffff',
        'on-primary-fixed': '#0d1c32',
        background: '#fbf9fb',
        'tertiary-fixed-dim': '#e7bf99',
        'primary-fixed': '#d6e3ff',
        'inverse-surface': '#303032',
        'on-secondary-fixed': '#001a41',
        'primary-container': '#0d1c32',
        'inverse-on-surface': '#f2f0f2',
        'secondary-fixed': '#d8e2ff',
        'on-surface': '#1b1b1d',
        'surface-container': '#efedef',
        'surface-tint': '#515f78',
        'on-secondary-fixed-variant': '#004493',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'on-background': '#1b1b1d',
        'inverse-primary': '#b9c7e4',
        'tertiary-container': '#2b1701',
        'surface-dim': '#dbd9db',
        'on-secondary-container': '#fefcff',
        error: '#ba1a1a',
        'on-surface-variant': '#44474d',
        'secondary-fixed-dim': '#adc7ff',
        outline: '#75777e',
        primary: '#000000',
        'outline-variant': '#c5c6cd',
        secondary: '#0059bb',
        'surface-variant': '#e4e2e4',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-low': '#f5f3f5',
        'error-container': '#ffdad6',
        'secondary-container': '#0070ea',
        'surface-container-lowest': '#ffffff',
        surface: '#fbf9fb',
        'surface-bright': '#fbf9fb',
        'on-tertiary-container': '#9f7d5b',
        'surface-container-highest': '#e4e2e4',
        'on-tertiary-fixed-variant': '#5d4124',
        'tertiary-fixed': '#ffdcbd',
        'primary-fixed-dim': '#b9c7e4',
        tertiary: '#000000',
        'on-tertiary-fixed': '#2b1701',
        'on-primary-container': '#76849f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        xxl: '48px',
        '3xl': '64px',
      },
      maxWidth: {
        '8xl': '1280px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        h1: ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h4: ['15px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['18px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '1.2', fontWeight: '500' }],
        h2: ['20px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
