spring.application.name=app

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/bidforge}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}

#spring.datasource.url=jdbc:postgresql://ep-withered-wave-amaiei1v-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_Zf2YmsuNGyd5

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.port=8080
server.error.include-stacktrace=never

jwt.secret=${JWT_SECRET:bidforge-local-dev-secret-key-replace-in-production-xxxxxxx}
jwt.expiration=900000

//stipe
stripe.webhook-secret=whsec_beb21140e0deac31503e41a561bf15fcf7aac16beefb7713f0a0542b516fdbc
stripe.secret-key=${STRIPE_SECRET_KEY:sk_test_51TSy12F6cmiAmy8CxwLfyHYds0lq0ZI04o7b7gHui5XLqGTwdlIAvSOb2ThFv1W7n2XeWpZhqbKuNL1SHrZfw1bg00R3D9ismj}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY:pk_test_51TSy12F6cmiAmy8CXFoP0MpnDIhKeLSyAxe5SQPOrhyzalxMBXg6WnfcemssVtz0Y6yurHdnMJrIBAL7oO51UQKJ00xr1Qnv9o}