ALTER TABLE notification_preference
    ADD COLUMN IF NOT EXISTS dispute_opened BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS user_banned BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS new_user_registered BOOLEAN NOT NULL DEFAULT TRUE;
